[llm]
base_url = "http://localhost:8082/v1/"
api_key = "xxxxxxxxxxxxxxxxxxxxxxx"
model = "deepseek-r1-search"

hy_user = "xxxxxxxx"
agent_id = "xxxxxxxxx"
chat_id = ""
should_remove_conversation = false

[tts]
source = "dashscope"

[tts.dashscope]
api_key = "sk-e1xxxxxxxxxxxxxxx"
model = "cosyvoice-v2"
voices = ["loongbella_v2", "longcheng_v2"]

[tts.hailuo]
api_key = "xxxxxxxxxxxxxxx"
base_url = "http://127.0.0.1:8080/v1"
voices = ["Podcast_girl", "male-botong"]

[chart]
js_host = "/home/FinVizAI/assets/v5/"
workers = 4
source = "bg"
windows = 100

[video]
fps = 24
background_audio = "./assets/audios/bgm.mp3"
background_audio_volume = 0.2
width = 1080
height = 1920
codec="libx264"
threads = 1

[video.subtitle]
font = "./assets/fonts/msyhbd.ttc"
width_ratio = 0.8
font_size_ratio = 18
position_ratio = 0.88
color = "#333"
stroke_color = "black"
stroke_width = 0
text_align = "center"
interval = 0.2

[video.title]
font = "./assets/fonts/msyhbd.ttc"
width_ratio = 0.8
font_size_ratio = 13
position_ratio = 0.5
color = "#2E8B57"
bg_color = "#FAFAFA"
stroke_color = "black"
stroke_width = 0
text_align = "center"
interval = 0.5
bg_image_opacity = 0.5

[video.report]
interval = 5
